= Urania documentation
Funcool
0.1.0
:toc: left
:numbered:
:idseparator: -
:idprefix:
:sectlinks:
:source-highlighter: pygments
:pygments-style: friendly

== Introduction

Oftentimes, your business logic relies on remote data that you need
to fetch from different sources: databases, caches, web services or
3rd party APIs, and you can't mess things up. Urania helps you to keep
your business logic clear of low-level details while performing efficiently:

- batch multiple requests to the same data source
- request data from multiple data sources concurrently
- cache previous requests

Having all this gives you the ability to access remote data sources in a
concise and consistent way, while the library handles batching and overlapping
requests to multiple data sources behind the scenes.

== Installation

The simplest way to use _urania_ in a Clojure project is by including
it as a dependency in your *_project.clj_*:

[source,clojure]
----
[funcool/urania "0.1.0"]
----

=== Limitations

- requires Java 8 when used from Clojure due to its use of java.util.concurrent.CompletableFuture
- works with the promesa library only (if you use other async mechanism like futures you can easily turn your code to be compatible with promises)
- assumes your operations with data sources are "side-effects free", so you don't really care about the order of fetches
- you need enough memory to store the whole data fetched during a single run! call (in case it's impossible you should probably look into other ways to solve your problem, i.e. data stream libraries)

== User Guide

=== Rationale

A core problem of many systems is balancing expressiveness against performance.

Let's imagine the problem of calculating the number of friends in common that two users have, where
we fetch the user data from a remote data source.

[source, clojure]
----
(require '[clojure.set :refer [union intersection]])

(defn count-common
  [a b]
  (count (intersection a b)))

(defn count-common-friends
  [x y]
  (count-common (friends-of x)
		(friends-of y)))

(num-common-friends 1 2)
----

Here, `(friends-of x)` and `(friends-of y)` are independent, and you want it to be fetched concurrently in a
single batch. Furthermore, if `x` and `y` refer to the same person, you don't want to redundantly re-fetch
their friend list.

*Urania* allows your data fetches to be implicitly concurrent with little changes to the original code:

[source, clojure]
----
(require '[urania.core :as u])

(defn num-common-friends [x y]
  (u/fmap count-common
           (friends-of x)
           (friends-of y)))

(u/run! (num-common-friends 1 2))
----

As you may have noticed, Urania does so separating the data fetch declaration from its execution.

=== Fetching data

Data fetching is usually asynchronous and/or has the possibility of error, that's why Urania uses the
Promise type available in the Promesa library as its result abstraction.

We'll start by writing a small function for emulating data sources with unpredictable latency. In
ClojureScript:

[source, clojure]
----
(require '[promesa.core :as prom])

(defn remote-req [id result]
  (prom/promise
    (fn [resolve reject]
      (let [wait (rand 1000)]
       (println "-->" id ".." wait)
       (js/setTimeout #(do (println "<--" id)
                           (resolve result))
                      wait)))))
----

and in Clojure:

[source, clojure]
----
(require '[promesa.core :as prom])

(defn remote-req [id result]
  (prom/promise
    (fn [resolve reject]
      (let [wait (rand 1000)]
       (println "-->" id ".." wait)
       (Thread/sleep wait)
       (println "<--" id)
       (resolve result)))))
----

Now, we define our data sources as record that implement Urania's `DataSource` protocol. This protocol
has a single function, `fetch`, that must return a promise.

[source, clojure]
----
(require '[urania.core :as u])

(defrecord FriendsOf [id]
  u/DataSource
  (fetch [_]
    (remote-req id (set (range id)))))

(defn friends-of [id]
  (FriendsOf. id))
----


=== Protocols

==== DataSource
==== LabeledSource
==== BatchedSource

== Examples

=== The N+1 selects problem
=== HTTP calls

== More resources

=== Talks

- "Reinventing Haxl: Efficient, Concurrent and Concise Data Access" at EuroClojure 2015: [Video](https://goo.gl/masrsz), [Slides](https://goo.gl/h4Zuvr)

== Development

=== Contributing

== Acknowledgements

Urania is based on the initial work on Muse by Alexey Kachayev. It is also heavily inspired by:

- Haxl (https://github.com/facebook/Haxl) - Haskell library, Facebook, open-sourced
- Stitch (https://www.youtube.com/watch?v=VVpmMfT8aYw) - Scala library, Twitter, not open-sourced

== License

[source,text]
----
Copyright (c) 2015 Alexey Kachayev
Copyright (c) 2015 Alejandro Gómez <alejandro@dialelo.com>
Copyright (c) 2015 Andrey Antukh <niwi@niwi.nz>

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
----
